# Generated by Django 3.1.2 on 2020-10-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201014_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password1',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='password2',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
