# Generated by Django 3.1.2 on 2020-10-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0008_auto_20201015_2200'),
        ('accounts', '0005_auto_20201015_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
