# Generated by Django 3.1.2 on 2020-10-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Pictures'),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_title',
            field=models.CharField(default=None, max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
