# Generated by Django 3.1.2 on 2020-10-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201015_1929'),
        ('travel_app', '0006_travel_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='Travelers', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='travel_journal',
            name='travelers_in_journal',
            field=models.ManyToManyField(blank=True, related_name='Travelers_in_journal', to='accounts.Account'),
        ),
    ]
