# Generated by Django 3.1.2 on 2020-10-15 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_app', '0007_auto_20201015_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='Travelers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travel_journal',
            name='travelers_in_journal',
            field=models.ManyToManyField(blank=True, related_name='Travelers_in_journal', to=settings.AUTH_USER_MODEL),
        ),
    ]
