# Generated by Django 3.1.2 on 2020-10-20 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_app', '0009_auto_20201020_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='travelers',
        ),
        migrations.AddField(
            model_name='travel',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
